name: UI Tests

on:
    workflow_call:
        inputs:
            config-path:
                required: false
                type: string
            baseUrl:
                required: true
                type: string
            waitCheckName:
                required: true
                type: string

jobs:
    ui-tests:
        name: Cypress remote run
        runs-on: [ self-hosted, Linux, medium ]
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        
        steps:

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Cypress install
                uses: cypress-io/github-action@v5
                with:
                    # just perform install
                    runTests: false

            -   name: Wait for build to succeed # https://github.com/fountainhead/action-wait-for-check
                uses: fountainhead/action-wait-for-check@v1.1.0
                id: wait-for-build
                with:
                    ref: ${{ github.event.pull_request.head.sha || github.sha }}
                    checkName: ${{ inputs.waitCheckName }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    #wait-interval: 10

            -   name: cypress
                uses: cypress-io/github-action@v5
                if: steps.wait-for-build.outputs.conclusion == 'success'
                env:
                    APP_URL: ${{ inputs.CYPRESS_BASE_URL }}
                    COMMIT_SHA: ${{ env.COMMIT_SHA }}
                    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                    CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
                    CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
                    CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
                    #COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
                    DEBUG: '@cypress/github-action'
                with:
                    config: pageLoadTimeout=100000,baseUrl=${{ inputs.baseUrl }}
                    install: false
                    # Linux and MacOS
                    #start: doppler run --command="export APP_URL=${{ inputs.baseUrl }} && cypress run"
                    # Takes precedences on Windows
                    #start-windows: export APP_URL=${{ inputs.baseUrl }} && cypress run
                    # browser: ${{ matrix.browser }}
                    # headless: true
                    record: true
                    parallel: false
                    #group: github action ${{ matrix.browser }}
                    tag: ${{ github.event_name }}
                    # wait-on: ${{ inputs.baseUrl }}
                    spec: |
                        cypress/e2e/local/*cy.js

            -   name: Cypress infos
                run: |
                    echo Cypress finished with: ${{ steps.cypress.outcome }}
                    echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
                 
            #            -   name: Upload screenshots
            #                uses: actions/upload-artifact@v3
            #                if: failure()
            #                with:
            #                    name: ${{ github.job }}-screenshots
            #                    path: cypress/screenshots
            
            # uses too much storage space
            #            -   name: Upload videos
            #                uses: actions/upload-artifact@v3
            #                if: failure()
            #                with:
            #                    name: ${{ github.job }}-videos
            #                    path: cypress/videos

            -   name: Upload report
                uses: actions/upload-artifact@v3
                if: failure()
                with:
                    name: ${{ github.job }}-reports
                    path: cypress/reports
            
            # Doesn't work
            #            -   name: 'Upload screenshots and videos to Slack'
            #                uses: trymbill/cypress-slack-video-upload-action@v1.3.0
            #                if: failure()
            #                with:
            #                    token: ${{ secrets.SLACK_TOKEN }}
            #                    channels: 'emergency'
            #                    message-text: 'Cypress tests failed! They have been placed in this thread, good luck.'
            
            #    TODO: Fix Error: Cannot find the pull request ID.                
            #            -   name: Cypress report
            #                uses: dmitry/cypress-report-action@v1
            #                with:
            #                    token: ${{ secrets.GITHUB_TOKEN }}
            #                    pathname: cypress/reports/mocha/mochawesome.json
            #                if: always()

            -   name: execute Ghost Inspector suite
                uses: docker://ghostinspector/cli
                with:
                    args: suite execute 5c0a8c83c4036f64df153b3f \
                        --apiKey ${{ secrets.GI_API_KEY }} \
                        --startUrl ${{ inputs.CYPRESS_BASE_URL }} \
                        --errorOnFail

            -   name: Do something with a failing build
                if: steps.wait-for-build.outputs.conclusion == 'failure'
                run: exit 1
