steps:
    -   name: gcr.io/cloud-builders/docker
        args:
            - build
            - '-t'
            - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
            - .
            - '-f'
            - Dockerfile
            - '--build-arg=COMMIT_SHA'
            - '--build-arg=BRANCH_NAME'
            - '--build-arg=BUILD_ID'
            - '--build-arg=TEST_FOLDER'
            - '--build-arg=UNIT_DOPPLER_TOKEN'
            - '--build-arg=STAGING_DOPPLER_TOKEN'
            - '--build-arg=CYPRESS'
        id: Build
        env:
            - 'APP_ENV=testing'
            - 'COMMIT_SHA=$COMMIT_SHA'
            - 'BRANCH_NAME=$BRANCH_NAME'
            - 'BUILD_ID=$BUILD_ID'
            - 'STAGING_DOPPLER_TOKEN=$_STAGING_DOPPLER_TOKEN'
            - 'UNIT_DOPPLER_TOKEN=$_UNIT_DOPPLER_TOKEN'
            - 'TEST_FOLDER=$_TEST_FOLDER'
            - 'CYPRESS=$_CYPRESS'
images:
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
    substitutionOption: ALLOW_LOOSE
substitutions:
    _PLATFORM: managed
    _LABELS: gcb-trigger-id=73604020-7aff-44a9-a2fc-97830e0d0652
    _TRIGGER_ID: 73604020-7aff-44a9-a2fc-97830e0d0652
    _DEPLOY_REGION: us-central1
    _GCR_HOSTNAME: us.gcr.io
tags:
    - phpunit
