steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cd-api-laravel8:$_CI_COMMIT_SHA', '.']
  env:
    - 'APP_ENV=production'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cd-api-laravel8:$_CI_COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['beta','run', 'deploy', 'laravel1', '--image', 'gcr.io/$PROJECT_ID/laravel:$_CI_COMMIT_SHA', '--region', 'us-central1', '--port','80','--vpc-connector','default']
images: ['gcr.io/$PROJECT_ID/cd-api-laravel8:$_CI_COMMIT_SHA','--allow-unauthenticated']
logsBucket: 'gs://curedao_cloudbuild/laravel-log'
