name: Import Connections
on:
    # The workflow must be on the default branch to work. 
    # If you want to use code from another branch, you can still do that by passing the branch name to the checkout action:
    # https://github.com/orgs/community/discussions/26374
    # https://crontab.guru/every-5-minutes
    schedule:
        - cron: "*/5 * * * *" # Every x minutes
jobs:
    import-connections:
        uses: ./.github/workflows/reusable-job.yml
        with:
            command: doppler run --command="php scripts/jobs/import_connections.php"
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRODUCTION }}
