name: Analyze Users
on:
    # The workflow must be on the default branch to work. 
    # If you want to use code from another branch, you can still do that by passing the branch name to the checkout action:
    # https://github.com/orgs/community/discussions/26374
    # https://crontab.guru/every-5-minutes
    schedule:
        - cron: "*/30 * * * *" # Every x minutes
jobs:
    analyze-users:
        uses: ./.github/workflows/reusable-job.yml
        with:
            command: doppler run --command="php scripts/jobs/analyze_users.php"
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRODUCTION }}
