name: Reusable Job Workflow

on:
    workflow_call:
        inputs:
            config-path:
                required: false
                type: string
            command:
                required: true
                type: string
        secrets:
            DOPPLER_TOKEN:
                required: true
                
jobs:
    command:
        # Container operations are only supported on Linux runners
        runs-on: [ self-hosted, Linux, slow ]
        container:
            #image: curedao/php-8.1-apache-buster-xdebug-opcache-composer-pgsql:latest
            # Can't get consistent highchart exports from curedao/php-8.1-apache-buster-xdebug-opcache-composer-pgsql:latest
            # in local environment even though both docker containers version seem to work
            image: kirschbaumdevelopment/laravel-test-runner:8.1-couch-mongo
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: false
        
        steps:
            -   name: Output ENV
                run: printenv
            -   name: Output USER
                run: echo "User is $(whoami) and directory is $(pwd)"
            -   name: Remove .env
                run: rm .env || true
#            -   name: Get Actions user id
#                id: get_uid
#                run: |
#                    actions_user_id=`id -u $USER`
#                    echo $actions_user_id
#                    echo "uid=$actions_user_id" >> $GITHUB_OUTPUT
#            -   name: Correct Ownership in GITHUB_WORKSPACE directory
#                uses: peter-murray/reset-workspace-ownership-action@v1
#                with:
#                    user_id: ${{ steps.get_uid.outputs.uid }}
            -   name: Install Doppler CLI
                uses: dopplerhq/cli-action@v2
            -   name: List secret names from Doppler
                run: doppler secrets --only-names
                env:
                    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
                    RUNNER: ${{ runner.name }}
                    APP_DEBUG: ${{ runner.debug }}
                    RUNNER_TEMP: ${{ runner.temp }} # The path to a temporary directory on the runner. This directory is emptied at the beginning and end of each job. Note that files will not be removed if the runner's user account does not have permission to delete them.
                    RUNNER_OS: ${{ runner.os }} # The operating system of the runner executing the job. Possible values are Linux, Windows, or macOS
                    RUNNER_TOOL_CACHE: ${{ runner.tool_cache }} # The path to the directory containing preinstalled tools for GitHub-hosted runners. 
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 1
                    clean: false
            -   name: Copy Test DB
                run: |
                    cp tests/fixtures/qm_test.sqlite storage/qm_test.sqlite
            -   name: Install composer dependencies
                run: |
                    echo "I am $(whoami) && git stash && git reset --hard && ls -la"
            -   name: Install Doppler
                run: |
                    (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh
            -   name: Install composer dependencies
                run: |
                    doppler run --command="composer install"
                timeout-minutes: 2
                env:
                    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
                    RUNNER: ${{ runner.name }}
                    APP_DEBUG: ${{ runner.debug }}
                    RUNNER_TEMP: ${{ runner.temp }} # The path to a temporary directory on the runner. This directory is emptied at the beginning and end of each job. Note that files will not be removed if the runner's user account does not have permission to delete them.
                    RUNNER_OS: ${{ runner.os }} # The operating system of the runner executing the job. Possible values are Linux, Windows, or macOS
                    RUNNER_TOOL_CACHE: ${{ runner.tool_cache }} # The path to the directory containing preinstalled tools for GitHub-hosted runners. 
            -   name: Make phantomjs executable
                run: |
                    chmod +x ./vendor/mikepsinn/php-highcharts-exporter/phantomjs
                env:
                    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
                    RUNNER: ${{ runner.name }}
                    APP_DEBUG: ${{ runner.debug }}
                    RUNNER_TEMP: ${{ runner.temp }} # The path to a temporary directory on the runner. This directory is emptied at the beginning and end of each job. Note that files will not be removed if the runner's user account does not have permission to delete them.
                    RUNNER_OS: ${{ runner.os }} # The operating system of the runner executing the job. Possible values are Linux, Windows, or macOS
                    RUNNER_TOOL_CACHE: ${{ runner.tool_cache }} # The path to the directory containing preinstalled tools for GitHub-hosted runners. 
            -   name: Run Job # https://github.com/mheap/phpunit-github-actions-printer 
                run:  ${{ inputs.command }}
                env:
                    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
                    RUNNER: ${{ runner.name }}
                    APP_DEBUG: ${{ runner.debug }}
                    RUNNER_TEMP: ${{ runner.temp }} # The path to a temporary directory on the runner. This directory is emptied at the beginning and end of each job. Note that files will not be removed if the runner's user account does not have permission to delete them.
                    RUNNER_OS: ${{ runner.os }} # The operating system of the runner executing the job. Possible values are Linux, Windows, or macOS
                    RUNNER_TOOL_CACHE: ${{ runner.tool_cache }} # The path to the directory containing preinstalled tools for GitHub-hosted runners. 
