name: UI Tests

on:
    workflow_call:
        inputs:
            config-path:
                required: false
                type: string
            CYPRESS_BASE_URL:
                required: true
                type: string
            waitCheckName:
                required: true
                type: string
        secrets:
            DOPPLER_TOKEN:
                required: true
            DD_API_KEY:
                required: true

jobs:
    ui-tests:
        name: UI
        runs-on: [ self-hosted, Linux, cypress ]
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        
        steps:
                  
            - name: Fixing permissions error
              run: |
                  sudo chown -R $USER:$USER /home/m/actions-runners/curedao-api/_work/curedao-api/curedao-api || true      

            -   name: Checkout
                uses: actions/checkout@v3
                
            - name: Set $HOME variable if not set already
              run: |
                  [ -z "$HOME" ] && echo "HOME=/root" >> $GITHUB_ENV || echo "HOME is $HOME"
                
            -   name: Install Doppler
                run: |
                    (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh

            -   name: List secret names from Doppler
                run: doppler secrets --only-names
                env:
                    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
                    RUNNER: ${{ runner.name }}
                    APP_DEBUG: ${{ runner.debug }}
                    RUNNER_TEMP: ${{ runner.temp }} # The path to a temporary directory on the runner. This directory is emptied at the beginning and end of each job. Note that files will not be removed if the runner's user account does not have permission to delete them.
                    RUNNER_OS: ${{ runner.os }} # The operating system of the runner executing the job. Possible values are Linux, Windows, or macOS
                    RUNNER_TOOL_CACHE: ${{ runner.tool_cache }} # The path to the directory containing preinstalled tools for GitHub-hosted runners. 
            
            -   name: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
                run: |
                    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
                    
            -   name: echo user
                run: |
                    echo "I am $(whoami)"
                    
            -   name: source ~/.profile
                run: |
                    source ~/.profile 

            -   name: nvm install v16.19.0
                run: |
                    nvm install v16.19.0 || true

            -   name: nvm use v16.19.0
                run: |
                    nvm use v16.19.0 || true

            -   name: npm install -g cypress --unsafe-perm
                run: |
                    npm install -g cypress --unsafe-perm || true

            -   name: npm install
                run: |
                    npm install

            -   name: cypress install
                run: |
                    cypress install

            -   name: Wait for build to succeed # https://github.com/fountainhead/action-wait-for-check
                uses: fountainhead/action-wait-for-check@v1.1.0
                id: wait-for-build
                with:
                    ref: ${{ github.event.pull_request.head.sha || github.sha }}
                    checkName: ${{ inputs.waitCheckName }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    #wait-interval: 10
                
            -   name: cypress
                run: |
                    cypress run --record --key 662e64b2-03c7-4d07-9fcb-25f72d37b257 --browser electron --spec "cypress/e2e/local/*cy.js"
                timeout-minutes: 20
                env:
                    CYPRESS_BASE_URL: ${{ inputs.CYPRESS_BASE_URL }}
                    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
                    RUNNER: ${{ runner.name }}
                    APP_DEBUG: ${{ runner.debug }}
                    RUNNER_TEMP: ${{ runner.temp }} # The path to a temporary directory on the runner. This directory is emptied at the beginning and end of each job. Note that files will not be removed if the runner's user account does not have permission to delete them.
                    RUNNER_OS: ${{ runner.os }} # The operating system of the runner executing the job. Possible values are Linux, Windows, or macOS
                    RUNNER_TOOL_CACHE: ${{ runner.tool_cache }} # The path to the directory containing preinstalled tools for GitHub-hosted runners. 
#                    
#            -   name: Upload screenshots
#                uses: actions/upload-artifact@v3
#                if: failure()
#                with:
#                    name: ${{ github.job }}-screenshots
#                    path: cypress/screenshots

# uses too much storage space
#            -   name: Upload videos
#                uses: actions/upload-artifact@v3
#                if: failure()
#                with:
#                    name: ${{ github.job }}-videos
#                    path: cypress/videos

            -   name: Cypress infos
                run: |
                    echo Cypress finished with: ${{ steps.cypress.outcome }}
                    echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
                    
            -   name: Upload report
                uses: actions/upload-artifact@v3
                if: failure()
                with:
                    name: ${{ github.job }}-reports
                    path: cypress/reports

# Doesn't work
#            -   name: 'Upload screenshots and videos to Slack'
#                uses: trymbill/cypress-slack-video-upload-action@v1.3.0
#                if: failure()
#                with:
#                    token: ${{ secrets.SLACK_TOKEN }}
#                    channels: 'emergency'
#                    message-text: 'Cypress tests failed! They have been placed in this thread, good luck.'

#    TODO: Fix Error: Cannot find the pull request ID.                
#            -   name: Cypress report
#                uses: dmitry/cypress-report-action@v1
#                with:
#                    token: ${{ secrets.GITHUB_TOKEN }}
#                    pathname: cypress/reports/mocha/mochawesome.json
#                if: always()

            -   name: execute Ghost Inspector suite
                uses: docker://ghostinspector/cli
                with:
                    args: suite execute 5c0a8c83c4036f64df153b3f \
                        --apiKey ${{ secrets.GI_API_KEY }} \
                        --startUrl ${{ inputs.CYPRESS_BASE_URL }} \
                        --errorOnFail

            -   name: npm install -g @datadog/datadog-ci
                run: |
                    npm install -g @datadog/datadog-ci || true
            -   name: Upload JUnit results to Datadog
                run: |
                    DATADOG_API_KEY=${{ secrets.DD_API_KEY }} DD_ENV=ci datadog-ci junit upload   --service ${{ inputs.test-folder }}   build/
                    
#            - uses: datadog/junit-upload-github-action@v1
#              with:
#                  api-key: ${{ secrets.DD_API_KEY }}
#                  service: ui-tests
#                  files: ./cypress/reports/junit/
                  
            -   name: Do something with a failing build
                if: steps.wait-for-build.outputs.conclusion == 'failure'
                run: exit 1
