on:
    push:
        branches:
            - 'feature/**'
            - 'dependabot/**'
name: Feature
jobs:
    dump_contexts_to_log:
        runs-on: ubuntu-latest
        steps:
            -   name: Dump GitHub context
                id: github_context_step
                run: echo '${{ toJSON(github) }}'
            -   name: Dump job context
                run: echo '${{ toJSON(job) }}'
            -   name: Dump steps context
                run: echo '${{ toJSON(steps) }}'
            -   name: Dump runner context
                run: echo '${{ toJSON(runner) }}'
            -   name: Dump strategy context
                run: echo '${{ toJSON(strategy) }}'
            -   name: Dump matrix context
                run: echo '${{ toJSON(matrix) }}'
    slim:
        uses: ./.github/workflows/reusable-phpunit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_TESTING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/SlimTests
    api:
        uses: ./.github/workflows/reusable-phpunit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_TESTING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/APIs
    connectors:
        uses: ./.github/workflows/reusable-phpunit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_TESTING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/ConnectorTests
    unit:
        uses: ./.github/workflows/reusable-phpunit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_TESTING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/UnitTests
    staging-a:
        uses: ./.github/workflows/reusable-staging-unit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/StagingUnitTests/A
    staging-b:
        uses: ./.github/workflows/reusable-staging-unit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/StagingUnitTests/B
    staging-c:
        uses: ./.github/workflows/reusable-staging-unit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/StagingUnitTests/C
    staging-d:
        uses: ./.github/workflows/reusable-staging-unit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/StagingUnitTests/D
    staging-analyzable:
        uses: ./.github/workflows/reusable-staging-unit.yml
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
            test-folder: tests/StagingUnitTests/Analyzable
    ui:
        uses: ./.github/workflows/reusable-ui-tests.yml
        with:
            CYPRESS_BASE_URL: "https://feature.quantimo.do"
            waitCheckName: 'feature-quantimo-do (curedao)'
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_FEATURE }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
