on:
    push:
        branches:
            - 'master'
name: Production UI Tests
jobs:
    dump_contexts_to_log:
        runs-on: ubuntu-latest
        steps:
            -   name: Dump GitHub context
                id: github_context_step
                run: echo '${{ toJSON(github) }}'
            -   name: Dump job context
                run: echo '${{ toJSON(job) }}'
            -   name: Dump steps context
                run: echo '${{ toJSON(steps) }}'
            -   name: Dump runner context
                run: echo '${{ toJSON(runner) }}'
            -   name: Dump strategy context
                run: echo '${{ toJSON(strategy) }}'
            -   name: Dump matrix context
                run: echo '${{ toJSON(matrix) }}'
    production-tests:
        uses: ./.github/workflows/reusable-ui-tests.yml
        with:
            CYPRESS_BASE_URL: "https://app.quantimo.do"
            waitCheckName: 'app-quantimo-do (curedao)'
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRODUCTION }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
