on:
    push:
        branches:
            - 'develop'
name: Staging UI Tests
env:
    DOCKER_USER: "mikepsinn"
    APP_NAME: "qm-api"
    CLOUDRON_SERVER: "my.cloudron.curedao.org"
    APP_DOMAIN: "staging.quantimo.do"
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    CLOUDRON_TOKEN: ${{ secrets.CLOUDRON_TOKEN }}
    VERSION: "${GITHUB_SHA::7}"

jobs:
    dump_contexts_to_log:
        runs-on: ubuntu-latest
        steps:
            -   name: Dump GitHub context
                id: github_context_step
                run: echo '${{ toJSON(github) }}'
            -   name: Dump job context
                run: echo '${{ toJSON(job) }}'
            -   name: Dump steps context
                run: echo '${{ toJSON(steps) }}'
            -   name: Dump runner context
                run: echo '${{ toJSON(runner) }}'
            -   name: Dump strategy context
                run: echo '${{ toJSON(strategy) }}'
            -   name: Dump matrix context
                run: echo '${{ toJSON(matrix) }}'
    build_push_image:
        runs-on: [ self-hosted, Linux ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Docker Build Push
                uses: rossmaclean/docker-build-push-action@v0.0.15
                with:
                    docker-user: ${{ env.DOCKER_USER }}
                    image-name: ${{ env.APP_NAME }}
                    dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
                    version: ${{ env.VERSION }}

    deploy:
        needs: build_push_image
        runs-on: [ self-hosted, Linux ]
        steps:
            -   name: Cloudron Deploy
                uses: rossmaclean/cloudron-deploy-action@v0.0.21
                with:
                    image: ${{ env.DOCKER_USER }}/${{ env.APP_NAME }}:${{ env.VERSION }}
                    app-domain: ${{ env.APP_DOMAIN }}
                    cloudron-server: ${{ env.CLOUDRON_SERVER }}
                    cloudron-token: ${{ env.CLOUDRON_TOKEN }}
                    install-if-missing: "true"
                    skip-backup: "false"
                    
    staging-tests:
        uses: ./.github/workflows/reusable-ui-tests.yml
        with:
            CYPRESS_BASE_URL: "https://staging.quantimo.do"
            waitCheckName: 'staging-quantimo-do (curedao)'
        secrets:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STAGING }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
